// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI8vfZUWKhrFlPBiCzUvdglzwk8cNt3CU',
    appId: '1:800049255852:web:78550aa3cb96ad64ef1609',
    messagingSenderId: '800049255852',
    projectId: 'checko-fd7f9',
    authDomain: 'checko-fd7f9.firebaseapp.com',
    storageBucket: 'checko-fd7f9.firebasestorage.app',
    measurementId: 'G-6NG50BZJES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIdxGsMjmxWb4zQn2b0bDNaH9RcuRahPM',
    appId: '1:800049255852:android:8cc7de2e7086d2ebef1609',
    messagingSenderId: '800049255852',
    projectId: 'checko-fd7f9',
    storageBucket: 'checko-fd7f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIveK7a4-pu3s1Kte46hswSCaK-3dbI_w',
    appId: '1:800049255852:ios:e085fd745daa2d90ef1609',
    messagingSenderId: '800049255852',
    projectId: 'checko-fd7f9',
    storageBucket: 'checko-fd7f9.firebasestorage.app',
    iosBundleId: 'com.example.checko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIveK7a4-pu3s1Kte46hswSCaK-3dbI_w',
    appId: '1:800049255852:ios:e085fd745daa2d90ef1609',
    messagingSenderId: '800049255852',
    projectId: 'checko-fd7f9',
    storageBucket: 'checko-fd7f9.firebasestorage.app',
    iosBundleId: 'com.example.checko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI8vfZUWKhrFlPBiCzUvdglzwk8cNt3CU',
    appId: '1:800049255852:web:84bcd5e8f6a41165ef1609',
    messagingSenderId: '800049255852',
    projectId: 'checko-fd7f9',
    authDomain: 'checko-fd7f9.firebaseapp.com',
    storageBucket: 'checko-fd7f9.firebasestorage.app',
    measurementId: 'G-DKQDN26X94',
  );
}
